### ISSUE TITLE
buildCSPHeaders Error

### ISSUE THREAD

**Issue by JLucasCAmorim** [trezy/next-safe#14]
After the installation, I tried to customize the config, and then I ran the next project. So, I got the following error:

![image](https://user-images.githubusercontent.com/27377264/142638397-7f78c8a3-2d7c-4d53-acda-ab4e14beaac5.png)

next: 11.1.2,
react: 17.0.2

Please let me know if you need more information.

Many thanks,

**Comment by JLucasCAmorim** [comment]
I've tested, and if you change the '??' to '||', it works fine!

**Comment by trezy** [comment]
Thanks for fixing this, @JLucasCAmorim! Reopening this issue until I can fix the release.
