### ISSUE TITLE
Built-in type declarations

### ISSUE THREAD

**Issue by anvelicon** [trezy/next-safe#30]
### Is your feature request related to a problem? Please describe.

The first time I encountered the package, I expected to use it with built-in type declarations.

### Describe the solution you'd like

It would be nice to see declarations added.

### Describe alternatives you've considered

There's no real alternatives for implementing Typescript types 😅

### Additional context

The creation of a simple `types.d.ts` would suffice, it should be quick to implement while keeping JavaScript as the main language.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by trezy** [comment]
Hmm... `tsd-jsdoc` should be generating types with the published package. I'll look into this and see what I can figure out.

**Comment by trezy** [comment]
Installing the latest version of the lib, I'm not actually getting the types. As it turns out, I created the `build-types` Yarn script, but I never actually implemented it for the release. 🤦🏻‍♂️

I'll get this fixed here shortly.
