### ISSUE TITLE
Does my static website need Content Security Policy?

### ISSUE THREAD

**Issue by kamal-choudhary** [trezy/next-safe#9]
Hi, thank you so much for the useful package.

I have a static blog website built using Next.js and Strapi headless CMS.

I recently came to know about the Content Security Policy.

But having really a hard time understanding it thoroughly.

I was reading articles about it online and some of them say that it is not required for a static website. 

https://csp.withgoogle.com/docs/why-csp.html

https://reesmorris.co.uk/blog/implementing-proper-csp-nextjs-styled-components

My website is an SSG (automatically generated static HTML +JSON).

The only place where the server is involved is the sitemap.xml file which is handled by (pages/api/sitemap.js). I can't generate it statically because of dynamic URLs coming from Strapi.

I have a cookie consent banner on the website and that is the only cookie I think besides Google Analytics & TruConversion Heatmap cookies. (If this is relevant)

I am planning to have a "contact" page on my website in the future and it will contain the contact form. Probably, the only place where users may input data.

I'll be very thankful to you if you suggest to me that whether I actually need a CSP or not.

**Comment by kamal-choudhary** [comment]
Hi @trezy,

I'm so sorry for the delayed response.

Yes, I completely agree with you that CSP is needed even if our website is static.

We have actually delayed this thing for now, but when I'll implement it on our website, I'll post my solution here.

So, anybody who comes here for help in the future will be able to get help from it.

Thank you so much for your time.

**Comment by nibtime** [comment]
I find the term 'static website' when talking about this confusing, given the meaning it has today.

When we talk about "static pages" in the context of Next, we usually mean those pages that use `getStaticProps`. Those pages aren't more secure or insecure towards XSS than "dynamic pages" with `getServerSideProps`, "static pages" are build-time prerendered, "dynamic-pages" are per-request prerendered. But both hydrate on the client and become fully interactive React apps. This means that on both you can in principle do things that are an invitation to XSS. The decisive thing is whether you load dynamic user content or not. 

Say you would `dangerouslySetInnerHtml` user comments fetched via API from your database without sanitizing them. If then someone sneaks in a script into your database that steals your users' session data by posting a comment, it doesn't matter what pre-rendering strategy was used before serving the page to them. That script will be loaded and executed on their client either way when they browse the comment section. 

So I would say the need for a CSP depends on the degree to which your website loads dynamic user content. The more your site does that, the more it would benefit from a strong CSP.

If your website is this:
```jsx
const MyWebsite = () => <h1>Hello World</h1>
export default MyWebsite 
```

a CSP would probably be overkill 😄 

I personally think of a strong and effective CSP as 2FA against XSS. Strict CSP3 with hash or nonce would reliably block the script from the scenario above. Yet you still would sanitize user input, just as you don't use "123" as a password even with 2FA enabled.
